blank_issues_enabled: false
contact_links:
  - name: ðŸ“ƒ Documentation
    url: https://muhammad-fiaz.github.io/zon.zig/
    about: Read the documentation for guides and API reference
  - name: ðŸ’¬ Discussions
    url: https://github.com/muhammad-fiaz/zon.zig/discussions
    about: Use discussions for questions and general support
